version: '3.9'

services:
  nettest:
    image: nettest:1
    build: .
    volumes:
      - type: bind
        source: ./app
        target: /app
      - type: bind
        source: ./ookla
        target: /root/.config/ookla